name: Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        default: dev
        type: choice
        options: [dev, prod]
      confirm:
        description: 'Type "destroy" to confirm'
        required: true
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  destroy:
    name: Destroy ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'
    permissions:
      id-token: write
      contents: read

    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Mask AWS account ID
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Mask allowed IP
        run: echo "::add-mask::${{ secrets.MY_IP_CIDR }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "~1.6"

      - name: Terraform Init
        working-directory: terraform/environments/${{ github.event.inputs.environment }}
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=eurika-${{ github.event.inputs.environment }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Destroy
        working-directory: terraform/environments/${{ github.event.inputs.environment }}
        env:
          TF_VAR_image_uri: ''
          TF_VAR_alb_allowed_cidr_blocks: '["${{ secrets.MY_IP_CIDR }}"]'
        run: terraform destroy -input=false -auto-approve
